-- ---------------------------------------------------------------------------
-- Agently — initial D1 schema
--
-- This file consolidates (and reconciles) the 17 legacy PostgreSQL migrations
-- that lived in `server/db/migrations`. Those migrations had three defects that
-- are fixed here:
--
--   1. Duplicate tables. `maintenance` (004) and `maintenance_requests` (007)
--      both modelled a maintenance request with different columns, ids and
--      enums. Only `maintenance_requests` (the richer model, used by the API)
--      survives.
--   2. A shadowed table. `messages` was created in 005 and then created *again*
--      in 013 with `CREATE TABLE IF NOT EXISTS`, so 013 silently no-op'd and the
--      richer messaging schema never existed. Messaging is defined once, here.
--   3. Type mismatches. 007 declared `property_id INTEGER REFERENCES
--      properties(id)` while `properties.id` is a UUID, and its seed rows used
--      integer ids that could never satisfy those foreign keys.
--
-- Conventions
--   * ids      — TEXT, generated by the application (crypto.randomUUID)
--   * money    — INTEGER minor units (kobo/cents); never floating point
--   * booleans — INTEGER 0/1
--   * times    — TEXT ISO-8601 UTC
--   * lists    — TEXT holding JSON
-- ---------------------------------------------------------------------------

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id                      TEXT PRIMARY KEY,
    name                    TEXT NOT NULL,
    email                   TEXT NOT NULL,
    password_hash           TEXT NOT NULL,
    role                    TEXT NOT NULL DEFAULT 'tenant'
                            CHECK (role IN ('tenant', 'landlord', 'agent', 'manager', 'admin')),
    phone                   TEXT,
    avatar_url              TEXT,
    verified                INTEGER NOT NULL DEFAULT 0,
    disabled_at             TEXT,
    last_login_at           TEXT,
    failed_login_attempts   INTEGER NOT NULL DEFAULT 0,
    locked_until            TEXT,
    created_at              TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL,
    user_agent      TEXT,
    ip              TEXT,
    expires_at      TEXT NOT NULL,
    revoked_at      TEXT,
    replaced_by     TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires ON refresh_tokens (expires_at);

CREATE TABLE IF NOT EXISTS verification_tokens (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL,
    purpose     TEXT NOT NULL CHECK (purpose IN ('email_verification', 'password_reset')),
    expires_at  TEXT NOT NULL,
    used_at     TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_verification_tokens_hash ON verification_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_verification_tokens_user ON verification_tokens (user_id, purpose);

-- ---------------------------------------------------------------------------
-- Properties
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS properties (
    id                      TEXT PRIMARY KEY,
    slug                    TEXT NOT NULL,
    title                   TEXT NOT NULL,
    description             TEXT,
    type                    TEXT NOT NULL
                            CHECK (type IN ('apartment', 'house', 'condo', 'townhouse', 'studio', 'room')),
    status                  TEXT NOT NULL DEFAULT 'available'
                            CHECK (status IN ('available', 'occupied', 'maintenance', 'unavailable', 'draft')),
    landlord_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    price_amount            INTEGER NOT NULL,          -- minor units per month
    currency                TEXT NOT NULL DEFAULT 'NGN',
    deposit_amount          INTEGER,
    minimum_lease_months    INTEGER,

    address_line1           TEXT NOT NULL,
    address_line2           TEXT,
    city                    TEXT NOT NULL,
    state                   TEXT NOT NULL,
    zip_code                TEXT NOT NULL,
    country                 TEXT NOT NULL DEFAULT 'Nigeria',
    latitude                REAL,
    longitude               REAL,

    bedrooms                INTEGER NOT NULL DEFAULT 0,
    bathrooms               REAL NOT NULL DEFAULT 0,
    area_sqft               INTEGER,
    year_built              INTEGER,

    amenities               TEXT NOT NULL DEFAULT '[]',
    images                  TEXT NOT NULL DEFAULT '[]',
    featured                INTEGER NOT NULL DEFAULT 0,
    available_from          TEXT,

    created_at              TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at              TEXT NOT NULL DEFAULT (datetime('now')),
    deleted_at              TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_properties_slug ON properties (slug);
CREATE INDEX IF NOT EXISTS idx_properties_landlord ON properties (landlord_id);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties (status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_properties_city ON properties (city, state);
CREATE INDEX IF NOT EXISTS idx_properties_price ON properties (price_amount);
CREATE INDEX IF NOT EXISTS idx_properties_featured ON properties (featured, created_at DESC);
-- Full-text search over the fields people actually type into the search box.
CREATE INDEX IF NOT EXISTS idx_properties_search ON properties (city, state, type, status, bedrooms, price_amount);

CREATE TABLE IF NOT EXISTS saved_searches (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    criteria    TEXT NOT NULL DEFAULT '{}',
    alert_enabled INTEGER NOT NULL DEFAULT 1,
    last_run_at TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_saved_searches_user ON saved_searches (user_id);

-- ---------------------------------------------------------------------------
-- Bookings
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bookings (
    id                  TEXT PRIMARY KEY,
    property_id         TEXT NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    tenant_id           TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    landlord_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    start_date          TEXT NOT NULL,
    end_date            TEXT,
    message             TEXT,
    status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'completed')),
    monthly_rent_amount INTEGER NOT NULL DEFAULT 0,
    deposit_amount      INTEGER,
    currency            TEXT NOT NULL DEFAULT 'NGN',
    decision_reason     TEXT,
    decided_at          TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now')),

    -- A tenant may not hold two live bookings for the same property.
    CHECK (tenant_id <> landlord_id)
);

CREATE INDEX IF NOT EXISTS idx_bookings_property ON bookings (property_id);
CREATE INDEX IF NOT EXISTS idx_bookings_tenant ON bookings (tenant_id);
CREATE INDEX IF NOT EXISTS idx_bookings_landlord ON bookings (landlord_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);
-- Partial unique index: at most one *active* booking per (property, tenant).
CREATE UNIQUE INDEX IF NOT EXISTS idx_bookings_active_unique
    ON bookings (property_id, tenant_id)
    WHERE status IN ('pending', 'approved');

-- ---------------------------------------------------------------------------
-- Maintenance
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS maintenance_requests (
    id                  TEXT PRIMARY KEY,
    property_id         TEXT NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    tenant_id           TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    landlord_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    contractor_id       TEXT REFERENCES users (id) ON DELETE SET NULL,

    title               TEXT NOT NULL,
    description         TEXT NOT NULL,
    category            TEXT NOT NULL
                        CHECK (category IN ('plumbing', 'electrical', 'hvac', 'appliance',
                                            'structural', 'pest_control', 'cleaning', 'other')),
    priority            TEXT NOT NULL DEFAULT 'medium'
                        CHECK (priority IN ('low', 'medium', 'high', 'emergency')),
    status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'assigned', 'in_progress',
                                          'completed', 'cancelled', 'rejected')),

    area_affected       TEXT,
    access_instructions TEXT,
    images              TEXT NOT NULL DEFAULT '[]',

    tenant_notes        TEXT,
    landlord_notes      TEXT,
    contractor_notes    TEXT,

    estimated_cost_amount INTEGER,
    actual_cost_amount    INTEGER,
    currency              TEXT NOT NULL DEFAULT 'NGN',

    assigned_at         TEXT,
    completed_at        TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_maintenance_property ON maintenance_requests (property_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_tenant ON maintenance_requests (tenant_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_landlord ON maintenance_requests (landlord_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_contractor ON maintenance_requests (contractor_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_status ON maintenance_requests (status);
CREATE INDEX IF NOT EXISTS idx_maintenance_priority ON maintenance_requests (priority);
CREATE INDEX IF NOT EXISTS idx_maintenance_created ON maintenance_requests (created_at DESC);

CREATE TABLE IF NOT EXISTS maintenance_history (
    id                      TEXT PRIMARY KEY,
    maintenance_request_id  TEXT NOT NULL REFERENCES maintenance_requests (id) ON DELETE CASCADE,
    action                  TEXT NOT NULL
                            CHECK (action IN ('created', 'status_changed', 'assigned',
                                              'note_added', 'cost_updated')),
    old_status              TEXT,
    new_status              TEXT,
    changed_by              TEXT REFERENCES users (id) ON DELETE SET NULL,
    notes                   TEXT,
    created_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_maintenance_history_request ON maintenance_history (maintenance_request_id, created_at);

-- ---------------------------------------------------------------------------
-- Documents (metadata only — bytes live in R2)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS documents (
    id              TEXT PRIMARY KEY,
    owner_id        TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    property_id     TEXT REFERENCES properties (id) ON DELETE SET NULL,
    name            TEXT NOT NULL,
    category        TEXT NOT NULL DEFAULT 'other'
                    CHECK (category IN ('lease', 'identity', 'proof_of_income', 'insurance',
                                        'inspection', 'receipt', 'other')),
    mime_type       TEXT NOT NULL,
    size_bytes      INTEGER NOT NULL,
    storage_key     TEXT NOT NULL,
    uploaded_at     TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_documents_owner ON documents (owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_property ON documents (property_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_documents_storage_key ON documents (storage_key);

-- ---------------------------------------------------------------------------
-- Messaging
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS conversations (
    id                  TEXT PRIMARY KEY,
    participant_one_id  TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    participant_two_id  TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    property_id         TEXT REFERENCES properties (id) ON DELETE SET NULL,
    last_message_at     TEXT,
    last_message_preview TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now')),

    CHECK (participant_one_id <> participant_two_id)
);

-- One conversation per unordered pair, per property.
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_pair
    ON conversations (MIN(participant_one_id, participant_two_id),
                      MAX(participant_one_id, participant_two_id),
                      IFNULL(property_id, ''));

CREATE INDEX IF NOT EXISTS idx_conversations_participants ON conversations (participant_one_id, participant_two_id);
CREATE INDEX IF NOT EXISTS idx_conversations_recent ON conversations (last_message_at DESC);

CREATE TABLE IF NOT EXISTS messages (
    id              TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    sender_id       TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    message_type    TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'system')),
    read_at         TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_unread ON messages (conversation_id, read_at) WHERE read_at IS NULL;

CREATE TABLE IF NOT EXISTS message_attachments (
    id          TEXT PRIMARY KEY,
    message_id  TEXT NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    document_id TEXT REFERENCES documents (id) ON DELETE SET NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_message_attachments_message ON message_attachments (message_id);

-- ---------------------------------------------------------------------------
-- Agent CRM
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS leads (
    id                      TEXT PRIMARY KEY,
    agent_id                TEXT REFERENCES users (id) ON DELETE SET NULL,
    first_name              TEXT NOT NULL,
    last_name               TEXT NOT NULL,
    email                   TEXT,
    phone                   TEXT,
    company                 TEXT,
    source                  TEXT NOT NULL DEFAULT 'website',
    property_id             TEXT REFERENCES properties (id) ON DELETE SET NULL,

    budget_min_amount       INTEGER,
    budget_max_amount       INTEGER,
    preferred_locations     TEXT NOT NULL DEFAULT '[]',
    preferred_property_types TEXT NOT NULL DEFAULT '[]',
    preferred_bedrooms      INTEGER,
    preferred_bathrooms     INTEGER,
    move_in_date            TEXT,

    status                  TEXT NOT NULL DEFAULT 'new'
                            CHECK (status IN ('new', 'contacted', 'interested', 'qualified',
                                              'viewing_scheduled', 'viewing_completed',
                                              'offer_made', 'closed_won', 'closed_lost')),
    priority                TEXT NOT NULL DEFAULT 'medium'
                            CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    lead_score              INTEGER NOT NULL DEFAULT 0,
    conversion_probability  INTEGER NOT NULL DEFAULT 0,
    estimated_commission_amount INTEGER,

    notes                   TEXT,
    last_contacted_at       TEXT,
    next_follow_up_at       TEXT,
    created_at              TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_leads_agent ON leads (agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_follow_up ON leads (next_follow_up_at);

CREATE TABLE IF NOT EXISTS showings (
    id                  TEXT PRIMARY KEY,
    lead_id             TEXT NOT NULL REFERENCES leads (id) ON DELETE CASCADE,
    property_id         TEXT NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
    agent_id            TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_name         TEXT NOT NULL,
    client_email        TEXT,
    client_phone        TEXT,
    property_address    TEXT NOT NULL,
    scheduled_date      TEXT NOT NULL,
    scheduled_time      TEXT NOT NULL,
    duration_minutes    INTEGER NOT NULL DEFAULT 60,
    status              TEXT NOT NULL DEFAULT 'scheduled'
                        CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show')),
    notes               TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_showings_agent ON showings (agent_id, scheduled_date);
CREATE INDEX IF NOT EXISTS idx_showings_lead ON showings (lead_id);

CREATE TABLE IF NOT EXISTS commissions (
    id                      TEXT PRIMARY KEY,
    agent_id                TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    lead_id                 TEXT REFERENCES leads (id) ON DELETE SET NULL,
    property_id             TEXT REFERENCES properties (id) ON DELETE SET NULL,
    deal_value_amount       INTEGER NOT NULL DEFAULT 0,
    commission_rate         REAL NOT NULL DEFAULT 0,
    commission_amount       INTEGER NOT NULL DEFAULT 0,
    currency                TEXT NOT NULL DEFAULT 'NGN',
    status                  TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'earned', 'paid', 'cancelled')),
    closing_date            TEXT,
    payment_date            TEXT,
    notes                   TEXT,
    created_at              TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_commissions_agent ON commissions (agent_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Vendor marketplace
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS contractors (
    id              TEXT PRIMARY KEY,
    user_id         TEXT REFERENCES users (id) ON DELETE SET NULL,
    business_name   TEXT NOT NULL,
    description     TEXT,
    categories      TEXT NOT NULL DEFAULT '[]',
    service_areas   TEXT NOT NULL DEFAULT '[]',
    hourly_rate_amount INTEGER,
    currency        TEXT NOT NULL DEFAULT 'NGN',
    rating          REAL NOT NULL DEFAULT 0,
    review_count    INTEGER NOT NULL DEFAULT 0,
    verified        INTEGER NOT NULL DEFAULT 0,
    phone           TEXT,
    email           TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_contractors_verified ON contractors (verified, rating DESC);

CREATE TABLE IF NOT EXISTS vendor_bookings (
    id                  TEXT PRIMARY KEY,
    contractor_id       TEXT NOT NULL REFERENCES contractors (id) ON DELETE CASCADE,
    requested_by        TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    maintenance_request_id TEXT REFERENCES maintenance_requests (id) ON DELETE SET NULL,
    scheduled_for       TEXT,
    description         TEXT,
    status              TEXT NOT NULL DEFAULT 'requested'
                        CHECK (status IN ('requested', 'confirmed', 'in_progress',
                                          'completed', 'cancelled')),
    quoted_amount       INTEGER,
    currency            TEXT NOT NULL DEFAULT 'NGN',
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_vendor_bookings_contractor ON vendor_bookings (contractor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendor_bookings_requester ON vendor_bookings (requested_by);

CREATE TABLE IF NOT EXISTS vendor_reviews (
    id              TEXT PRIMARY KEY,
    contractor_id   TEXT NOT NULL REFERENCES contractors (id) ON DELETE CASCADE,
    reviewer_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating          INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment         TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_vendor_reviews_unique ON vendor_reviews (contractor_id, reviewer_id);
CREATE INDEX IF NOT EXISTS idx_vendor_reviews_contractor ON vendor_reviews (contractor_id);

-- ---------------------------------------------------------------------------
-- Roommate matching
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roommate_profiles (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    headline        TEXT,
    bio             TEXT,
    age             INTEGER,
    occupation      TEXT,
    budget_min_amount INTEGER,
    budget_max_amount INTEGER,
    preferred_city  TEXT,
    smoking         INTEGER NOT NULL DEFAULT 0,
    pets            INTEGER NOT NULL DEFAULT 0,
    night_owl       INTEGER NOT NULL DEFAULT 0,
    cleanliness     INTEGER NOT NULL DEFAULT 3 CHECK (cleanliness BETWEEN 1 AND 5),
    social_level    INTEGER NOT NULL DEFAULT 3 CHECK (social_level BETWEEN 1 AND 5),
    verified        INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_roommate_profiles_user ON roommate_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_roommate_profiles_city ON roommate_profiles (preferred_city);

CREATE TABLE IF NOT EXISTS roommate_applications (
    id                  TEXT PRIMARY KEY,
    from_profile_id     TEXT NOT NULL REFERENCES roommate_profiles (id) ON DELETE CASCADE,
    to_profile_id       TEXT NOT NULL REFERENCES roommate_profiles (id) ON DELETE CASCADE,
    message             TEXT,
    status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'accepted', 'declined')),
    match_score         INTEGER,
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now')),

    CHECK (from_profile_id <> to_profile_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_roommate_applications_unique
    ON roommate_applications (from_profile_id, to_profile_id);
CREATE INDEX IF NOT EXISTS idx_roommate_applications_target ON roommate_applications (to_profile_id, status);

-- ---------------------------------------------------------------------------
-- Notifications & audit
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notifications (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type            TEXT NOT NULL,
    title           TEXT NOT NULL,
    body            TEXT,
    resource_type   TEXT,
    resource_id     TEXT,
    read_at         TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;

CREATE TABLE IF NOT EXISTS audit_logs (
    id              TEXT PRIMARY KEY,
    actor_id        TEXT REFERENCES users (id) ON DELETE SET NULL,
    action          TEXT NOT NULL,
    resource_type   TEXT NOT NULL,
    resource_id     TEXT,
    ip              TEXT,
    metadata        TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs (resource_type, resource_id);

-- ---------------------------------------------------------------------------
-- Idempotency — protects creates against double submits and queue retries
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS idempotency_keys (
    id              TEXT PRIMARY KEY,
    user_id         TEXT,
    scope           TEXT NOT NULL,
    response_json   TEXT NOT NULL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at      TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_idempotency_scope ON idempotency_keys (scope, id);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON idempotency_keys (expires_at);
