#!/usr/bin/env node
/**
 * Generates public/sitemap.xml after the client bundle is built.
 *
 * Search engines can only index what they can reach, and a client-rendered SPA
 * exposes no URLs at build time. This emits the static routes explicitly.
 *
 * Property URLs are NOT listed: they live in the database, not the repository,
 * and a sitemap built from stale data does more harm than good. To include them,
 * call the public search endpoint here (paginated) with VITE_API_URL set.
 *
 * Usage: node scripts/generate-sitemap.mjs
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const siteUrl = (process.env.VITE_SITE_URL ?? 'https://agently.app').replace(/\/+$/, '');
const today = new Date().toISOString().slice(0, 10);

/**
 * @type {Array<{ path: string; priority: string; changefreq: string }>}
 * Only publicly indexable routes belong here. Authenticated screens
 * (dashboard, bookings, admin, ...) are excluded on purpose.
 */
const routes = [
  { path: '/', priority: '1.0', changefreq: 'daily' },
  { path: '/properties', priority: '0.9', changefreq: 'hourly' },
  { path: '/about', priority: '0.6', changefreq: 'monthly' },
  { path: '/contact', priority: '0.5', changefreq: 'yearly' },
  { path: '/privacy', priority: '0.3', changefreq: 'yearly' },
  { path: '/terms', priority: '0.3', changefreq: 'yearly' },
];

const escapeXml = (value) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const urls = routes
  .map(
    ({ path, priority, changefreq }) => `  <url>
    <loc>${escapeXml(`${siteUrl}${path}`)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs on ${today}. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

mkdirSync(resolve(root, 'public'), { recursive: true });
writeFileSync(resolve(root, 'public/sitemap.xml'), xml, 'utf8');

console.log(`sitemap.xml: ${routes.length} URLs written for ${siteUrl}`);
